language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - 0.5
  - 0.6
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

notifications:
  email: false

script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("QPS")'
  - julia --check-bounds=yes --inline=no -e 'Pkg.test("QPS",
    coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("QPS")); Pkg.add("Coverage"); using Coverage;
    Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
